/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface TestGovernanceMessageInterface extends ethers.utils.Interface {
  functions: {
    "formatBatch(tuple[])": FunctionFragment;
    "isValidBatch(bytes)": FunctionFragment;
    "serializeCall(tuple)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "formatBatch",
    values: [{ to: BytesLike; data: BytesLike }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidBatch",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeCall",
    values: [{ to: BytesLike; data: BytesLike }]
  ): string;

  decodeFunctionResult(
    functionFragment: "formatBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeCall",
    data: BytesLike
  ): Result;

  events: {};
}

export class TestGovernanceMessage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TestGovernanceMessageInterface;

  functions: {
    formatBatch(
      _calls: { to: BytesLike; data: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<[string]>;

    isValidBatch(
      _msg: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    serializeCall(
      _call: { to: BytesLike; data: BytesLike },
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  formatBatch(
    _calls: { to: BytesLike; data: BytesLike }[],
    overrides?: CallOverrides
  ): Promise<string>;

  isValidBatch(_msg: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  serializeCall(
    _call: { to: BytesLike; data: BytesLike },
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    formatBatch(
      _calls: { to: BytesLike; data: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<string>;

    isValidBatch(_msg: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    serializeCall(
      _call: { to: BytesLike; data: BytesLike },
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    formatBatch(
      _calls: { to: BytesLike; data: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidBatch(
      _msg: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    serializeCall(
      _call: { to: BytesLike; data: BytesLike },
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    formatBatch(
      _calls: { to: BytesLike; data: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidBatch(
      _msg: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    serializeCall(
      _call: { to: BytesLike; data: BytesLike },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
