name: Bug report
description: File a bug report
labels: ["T-bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please ensure that the bug has not already been filed in the issue tracker.

        Thanks for taking the time to report this bug!
  - type: dropdown
    attributes:
      label: Package
      description: What package is the bug in?
      multiple: true
      options:
        - contracts-bridge
        - contracts-core
        - contracts-router
        - deploy
        - indexer
        - keymaster
        - local-environment
        - multi-provider
        - sdk-bridge
        - sdk-govern
        - sdk
        - not applicable (please describe)
    validations:
      required: true
  - type: input
    attributes:
      label: At a high level, what are you trying to do?
      placeholder: "For example: install sdk-bridge in my app"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: Please include relevant error messages as well.
    validations:
      required: true
