/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { BadRecipient1, BadRecipient1Interface } from "../BadRecipient1";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "handle",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610122806100206000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063ab2dc3f514602d575b600080fd5b60ea60048036036080811015604157600080fd5b63ffffffff823581169260208101359091169160408201359190810190608081016060820135640100000000811115607857600080fd5b820183602082011115608957600080fd5b8035906020019184600183028401116401000000008311171560aa57600080fd5b91908080601f0160208091040260200160405190810160405280939291908181526020018383808284376000920191909152509295506028945050505050565b00fea26469706673582212206d9fd4c9d27962a906d939c3861fa62e2d1f5b690b1d51ce53450f6c09d5b9a564736f6c63430007060033";

export class BadRecipient1__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BadRecipient1> {
    return super.deploy(overrides || {}) as Promise<BadRecipient1>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): BadRecipient1 {
    return super.attach(address) as BadRecipient1;
  }
  connect(signer: Signer): BadRecipient1__factory {
    return super.connect(signer) as BadRecipient1__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BadRecipient1Interface {
    return new utils.Interface(_abi) as BadRecipient1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BadRecipient1 {
    return new Contract(address, _abi, signerOrProvider) as BadRecipient1;
  }
}
