/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { BadRecipient2, BadRecipient2Interface } from "../BadRecipient2";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "handle",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610122806100206000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063ab2dc3f514602d575b600080fd5b60ea60048036036080811015604157600080fd5b63ffffffff823581169260208101359091169160408201359190810190608081016060820135640100000000811115607857600080fd5b820183602082011115608957600080fd5b8035906020019184600183028401116401000000008311171560aa57600080fd5b91908080601f01602080910402602001604051908101604052809392919081815260200183838082843760009201919091525092955060ea945050505050565b00fea26469706673582212208f5f12c011bc597c96a813469c861befa6d37d2111f1e102465c8c7b6fde2b3264736f6c63430007060033";

export class BadRecipient2__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BadRecipient2> {
    return super.deploy(overrides || {}) as Promise<BadRecipient2>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): BadRecipient2 {
    return super.attach(address) as BadRecipient2;
  }
  connect(signer: Signer): BadRecipient2__factory {
    return super.connect(signer) as BadRecipient2__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BadRecipient2Interface {
    return new utils.Interface(_abi) as BadRecipient2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BadRecipient2 {
    return new Contract(address, _abi, signerOrProvider) as BadRecipient2;
  }
}
