name: Local Environment Tests
on:
  push:
    paths:
      - "packages/local-environment/**"
      - ".github/workflows/local-environment-tests.yml"

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps: 
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Yarn Install
      run: |
        yarn install --immutable-cache;
        
    - name: Yarn Install
      run: |  
        yarn lint;

    - name: Yarn Bootup
      run: |
        yarn local-environment bootup

    - name: Run Integration Tests
      run: |
        yarn test:integration
      timeout-minutes: 50

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

    - name: Yarn Install
      run: |
        yarn install --immutable-cache;

    - name: Yarn Install
      run: |  
        yarn lint;

      - name: Yarn Bootup
        run: |
          yarn local-environment bootup

      - name: Run Unit Tests
        run: |
          yarn local-environment test:unit
        timeout-minutes: 30

    
