name: Local Environment Release
on: workflow_dispatch

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1 
        with:
          version: nightly

      - name: Yarn Install
        run: |
          yarn local-environment install

      - name: Yarn Lint
        run: |
          yarn local-environment lint

      - name: Yarn Build
        run: |
          yarn local-environment build

      - name: Yarn Bootup
        run: |
          yarn local-environment bootup

      - name: Run Unit Tests
        run: |
          yarn local-environment test:unit
        timeout-minutes: 30

      - name: Publish to NPM
        run: yarn local-environment npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
