version: "3.7"
services:
  indexer:
    image: kekonen/indexer:latest
    build: .
    restart: always
    command: yarn start:core
    env_file: .env
    environment:
      - PROGRAM=core
      - DATABASE_URL=postgresql://postgres:postgres@192.168.1.107:5432/postgres?connect_timeout=300&schema=public
    ports:
      - "9090:9090"
      - "9091:1337"

  api:
    image: kekonen/indexer:latest
    build: .
    restart: always
    command: yarn start:api
    ports:
      - "8080:9090"
      - "8081:3000"
    expose:
      - 8080
    env_file: .env
    environment:
      - PROGRAM=api
      - DATABASE_URL=postgresql://postgres:postgres@192.168.1.107:5432/postgres?connect_timeout=300&schema=public

  redis:
    image: redis:latest
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./redis-data:/data
    ports:
      - '6379:6379'
    expose:
      - 6379
